name: wpcid
on:
  push:
    branches: main
jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: get_version
        uses: bbonkr/get-version-action@v1.0.5
        with:
          project: "./package.json"
      - name: logging
        run: echo "Version=${{ steps.get_version.outputs.version }}"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: tadeoarmenta/wpcicd:latest, tadeoarmenta/wpcicd:${{ steps.get_version.outputs.version }}